student = input("Enter your name: ")
Qualification = input("Enter your Qualification: ")
place = input("Enter your place: ")
Mobile_number = int(input("Enter your Mobile number: "))
age = int(input("Enter your Age: "))
tenth_percentage = float(input("Enter your 10th percentage: "))
twelfth_percentage = float(input("Enter your 12th percentage: "))
cgp = float(input("Enter your CGPA: "))
height = int(input("Enter your height (cm): "))
weight = int(input("Enter your weight (kg): "))

print(student)
print(Qualification)
print(place)
print(Mobile_number)
print(age)
print(tenth_percentage)
print(twelfth_percentage)
print(cgp)
print(height)
print(weight)
